### ISSUE TITLE
[US055] - Adicionar elementos gráficos

### ISSUE THREAD

**Issue by weslley17w** [mdsreq-fga-unb/2023-2-BeachTennisCoordiMate#38]
# US055 - História do Usuário

## Descrição

Eu, como usuário-coordenador, desejo adicionar elementos gráficos a um drill para representar o treino em um exercício/circuito. 

## Critérios de Aceitação

- [x] Deve ser permitir adicionar elementos gráficos como jogadores, cano alterado, arco, cone e setas
- [x] Os elementos gráficos não podem ser sobrepostos na representação dos drills
- [x] O sistema deve permitir que o usuário adicione, no máximo, 50 elementos gráficos a um drill

## DoR

- [x] O requisito está declarado como uma história de usuário?
- [x] A história tem critérios de aceitação definidos?
- [x] A história tem valor de negócio estabelecido?
- [x] A história está de acordo com o modelo do INVEST?
- [x] A história foi estimada em pontos, levando em conta os critérios de aceitação?
- [x] A história tem representação no formato de um protótipo?
- [x] A história foi validada pelo cliente?

## DoD

- [x] Os critérios de aceitação foram desenvolvidos e verificados?
- [x] O código desenvolvido está de acordo com a arquitetura do projeto?
- [x] O código desenvolvido é responsivo com os modelos de tela estabelecidos para o projeto?
- [x] A funcionalidade desenvolvida foi revisada por um membro da equipe?
- [x] A funcionalidade está integrada ao sistema principal da aplicação?

**Comment by ArturRSA19** [comment]
**INVEST**: 

| **Independente** | **Negociável** | **Valorosa** | **Estimável** | **Pequena** | **Testável** |
|------------------|----------------|--------------|---------------|-------------|--------------|
| Sim              | Sim            | Sim          | Sim           | Sim         | Sim          |

**Comment by Victor-oss** [comment]
![Screenshot from 2023-11-20 20-10-27](https://github.com/mdsreq-fga-unb/2023-2-BeachTennisCoordiMate/assets/55855365/f0b02ab7-eec0-43f9-9401-63b03af605f2)
![Screenshot from 2023-11-20 20-10-38](https://github.com/mdsreq-fga-unb/2023-2-BeachTennisCoordiMate/assets/55855365/5adc83e4-90be-4931-9ac2-a0c267f0eb5d)
![Screenshot from 2023-11-20 20-11-02](https://github.com/mdsreq-fga-unb/2023-2-BeachTennisCoordiMate/assets/55855365/5aa7ff27-8570-494c-90b2-886620aa66b6)
![Screenshot from 2023-11-20 20-11-11](https://github.com/mdsreq-fga-unb/2023-2-BeachTennisCoordiMate/assets/55855365/1ff62207-d804-4387-82dc-027c7dcfed27)
