### ISSUE TITLE
[US056] - Deletar elementos gráficos

### ISSUE THREAD

**Issue by weslley17w** [mdsreq-fga-unb/2023-2-BeachTennisCoordiMate#39]
# US056 - Deletar elementos gráficos

## Descrição

Eu, como usuário coordenador, desejo deletar elementos gráficos de um drill para deletar um elemento adicionado erroneamente. 

## Critérios de Aceitação

- [x] O sistema deve permitir deletar elementos gráficos como jogadores, cano alterado, arco, cone e setas

**Comment by ArturRSA19** [comment]
**INVEST**: 

| **Independente** | **Negociável** | **Valorosa** | **Estimável** | **Pequena** | **Testável** |
|------------------|----------------|--------------|---------------|-------------|--------------|
| Sim              | Sim            | Sim          | Sim           | Sim         | Sim          |

**Comment by Victor-oss** [comment]
![Screenshot from 2023-11-20 20-13-57](https://github.com/mdsreq-fga-unb/2023-2-BeachTennisCoordiMate/assets/55855365/44deb084-15ee-456f-85b3-52f260487f3b)
![Screenshot from 2023-11-20 20-14-19](https://github.com/mdsreq-fga-unb/2023-2-BeachTennisCoordiMate/assets/55855365/eb6854b0-ac0a-44b4-8a41-9bacf80f0e36)
![Screenshot from 2023-11-20 20-14-39](https://github.com/mdsreq-fga-unb/2023-2-BeachTennisCoordiMate/assets/55855365/449f8135-4dce-41f8-b8c2-d06f249a9775)
