### ISSUE TITLE
[US057] - Editar drill 

### ISSUE THREAD

**Issue by weslley17w** [mdsreq-fga-unb/2023-2-BeachTennisCoordiMate#40]
# US057 - Editar drill

## Descrição

Eu, como usuário-coordenador, desejo editar as informações de um drill para corrigir erros. 

## Critérios de Aceitação

- [x] O sistema deve permitir editar os campos título, descrição e observações
- [x] O título deverá ter, no mínimo, 5 caracteres
- [x] A descrição do drill deverá ter, no máximo, 500 caracteres
- [x] O campo observações deverá ter, no máximo, 500 caracteres

## DoR

- [x] O requisito está declarado como uma história de usuário?
- [x] A história tem critérios de aceitação definidos?
- [x] A história tem valor de negócio estabelecido?
- [x] A história está de acordo com o modelo do INVEST?
- [x] A história foi estimada em pontos, levando em conta os critérios de aceitação?
- [x] A história tem representação no formato de um protótipo?
- [x] A história foi validada pelo cliente?

## DoD

- [x] Os critérios de aceitação foram desenvolvidos e verificados?
- [x] O código desenvolvido está de acordo com a arquitetura do projeto?
- [x] O código desenvolvido é responsivo com os modelos de tela estabelecidos para o projeto?
- [x] A funcionalidade desenvolvida foi revisada por um membro da equipe?
- [x] A funcionalidade está integrada ao sistema principal da aplicação?

**Comment by ArturRSA19** [comment]
**INVEST**: 

| **Independente** | **Negociável** | **Valorosa** | **Estimável** | **Pequena** | **Testável** |
|------------------|----------------|--------------|---------------|-------------|--------------|
| Sim              | Sim            | Sim          | Sim           | Sim         | Sim          |

**Comment by luciano-freitas-melo** [comment]
Não finalizado na sprint 12 - problemas de integração e dependência com outras histórias
Atualizado para sprint 13
- Alterado o pontos da história para 1, por conta que só falta integrar ao sistema

**Comment by luciano-freitas-melo** [comment]
DoD completado para a US
