### ISSUE TITLE
[US058] - Deletar drill

### ISSUE THREAD

**Issue by Victor-oss** [mdsreq-fga-unb/2023-2-BeachTennisCoordiMate#41]
# US058 -  Deletar drill

## Descrição

Eu, como usuário-coordenador, desejo deletar um drill obsoleto para não deixar drills obsoletos em um plano de aula.

## Critérios de Aceitação

- [x] Ao selecionar a opção de exclusão, o sistema deve solicitar uma confirmação antes de apagar o drill
- [x] O sistema deve fornecer uma notificação para o usuário confirmando o sucesso da ação

## DoR

- [x] O requisito está declarado como uma história de usuário?
- [x] A história tem critérios de aceitação definidos?
- [x] A história tem valor de negócio estabelecido?
- [x] A história está de acordo com o modelo do INVEST?
- [x] A história foi estimada em pontos, levando em conta os critérios de aceitação?
- [x] A história tem representação no formato de um protótipo?
- [x] A história foi validada pelo cliente?

## DoD

- [x] Os critérios de aceitação foram desenvolvidos e verificados?
- [x] O código desenvolvido está de acordo com a arquitetura do projeto?
- [x] O código desenvolvido é responsivo com os modelos de tela estabelecidos para o projeto?
- [x] A funcionalidade desenvolvida foi revisada por um membro da equipe?
- [x] A funcionalidade está integrada ao sistema principal da aplicação?

**Comment by JoaoBarreto03** [comment]
**INVEST**: 

| **Independente** | **Negociável** | **Valorosa** | **Estimável** | **Pequena** | **Testável** |
|------------------|----------------|--------------|---------------|-------------|--------------|
| Sim              | Sim            | Sim          | Sim           | Sim         | Sim          |

**Comment by Victor-oss** [comment]
![Screenshot from 2023-11-20 19-32-05](https://github.com/mdsreq-fga-unb/2023-2-BeachTennisCoordiMate/assets/55855365/2b3d9ba6-b270-48c0-8308-7981ff03e03c)
![Screenshot from 2023-11-20 19-32-14](https://github.com/mdsreq-fga-unb/2023-2-BeachTennisCoordiMate/assets/55855365/70f81d83-a2af-423c-b5ae-8801ab11c2b8)
![Screenshot from 2023-11-20 19-25-39](https://github.com/mdsreq-fga-unb/2023-2-BeachTennisCoordiMate/assets/55855365/0c8a6a8a-7876-466d-bea2-1d73a326a67d)

**Comment by luciano-freitas-melo** [comment]
Não finalizado na sprint 12 - problemas de integração e dependência com outras histórias
Atualizado para sprint 13

- [ ] Integrar drill ao plano de aula

**Comment by luciano-freitas-melo** [comment]
Todos os critérios de DoD foram atendidos para a US
