### ISSUE TITLE
[US059] - Editar drill

### ISSUE THREAD

**Issue by Victor-oss** [mdsreq-fga-unb/2023-2-BeachTennisCoordiMate#42]
# US059 - Editar drill

## Descrição

Eu, como usuário-coordenador, desejo editar as informações de um drill para corrigir um erro.

## Critérios de Aceitação

- [ ] O sistema deve permitir que o usuário altere os atributos do drill que não estão relacionados a representação do treino e que são: título, descrição e observações
- [ ] O sistema deve exibir uma notificação ao usuário confirmando que a ação foi realizada com sucesso

**Comment by JoaoBarreto03** [comment]
**INVEST**: 

| **Independente** | **Negociável** | **Valorosa** | **Estimável** | **Pequena** | **Testável** |
|------------------|----------------|--------------|---------------|-------------|--------------|
| Sim              | Sim            | Sim          | Sim           | Sim         | Sim          |
