### ISSUE TITLE
[US060] - Visualizar planos de aula

### ISSUE THREAD

**Issue by Victor-oss** [mdsreq-fga-unb/2023-2-BeachTennisCoordiMate#43]
# US060 - Visualizar planos de aula

## Descrição

Eu, como usuário-coordenador, desejo visualizar uma lista com todos os planos de aula para ter uma noção da quantidade de planos feitos.

## Critérios de Aceitação

- [x] O sistema deve exibir os títulos dos diferentes planos de aula de um usuário
- [x] O sistema deve permitir ao usuário pesquisar planos de aula por uma parte de seus títulos
- [x] O sistema deve permitir ao usuário informar um intervalo de tempo em dias (com um dia de início e um dia de fim) e filtrar os planos de aula cuja data de criação se encontram nesse intervalo
- [x] O sistema deve permitir que a pesquisa por parte do título e o filtro possam funcionar de maneira simultânea e alternada

**Comment by JoaoBarreto03** [comment]
**INVEST**: 

| **Independente** | **Negociável** | **Valorosa** | **Estimável** | **Pequena** | **Testável** |
|------------------|----------------|--------------|---------------|-------------|--------------|
| Sim              | Sim            | Sim          | Sim           | Sim         | Sim          |

**Comment by Victor-oss** [comment]
![Screenshot from 2023-11-20 19-42-12](https://github.com/mdsreq-fga-unb/2023-2-BeachTennisCoordiMate/assets/55855365/fbc7d3e7-caa1-47b1-b111-fdbfb5e7d12f)
![Screenshot from 2023-11-20 19-44-46](https://github.com/mdsreq-fga-unb/2023-2-BeachTennisCoordiMate/assets/55855365/2d410748-c10b-47e8-ab0b-6ed79749c67b)
![Screenshot from 2023-11-20 19-48-57](https://github.com/mdsreq-fga-unb/2023-2-BeachTennisCoordiMate/assets/55855365/e33ead33-1188-4c03-a61f-2db6f446fe01)
![Screenshot from 2023-11-20 19-53-37](https://github.com/mdsreq-fga-unb/2023-2-BeachTennisCoordiMate/assets/55855365/54f44658-3bc3-456d-b346-18878735e894)
![colocar](https://github.com/mdsreq-fga-unb/2023-2-BeachTennisCoordiMate/assets/55855365/d78585f2-9db1-4d96-86af-9aed680f38ca)
