### ISSUE TITLE
[US01] -  Criar conta de administrador

### ISSUE THREAD

**Issue by ArturRSA19** [mdsreq-fga-unb/2023-2-BeachTennisCoordiMate#45]
# US01 - Criar conta de administrador

## Descrição

Eu, como usuário-coordenador, desejo criar minha conta para administrar a arena

## Critérios de Aceitação

- [x] Ao acessar a página de cadastro, o usuário-coordenador deve fornecer as seguintes informações: nome, endereço de e-mail, senha e confirmação de senha.
- [x] O sistema deve validar se o endereço de e-mail fornecido é único e ainda não está registrado no sistema.
- [x] A senha e a confirmação de senha devem coincidir
- [x] O email deve estar no formato "nome@email.com"
- [x] Todos os campos devem ser obrigatórios
- [x] A senha deve ter no mínimo 6 caracteres
- [x] O nome deve ter no mínimo 4 caracteres

## DoR

- [x] O requisito está declarado como uma história de usuário?
- [x] A história tem critérios de aceitação definidos?
- [x] A história tem valor de negócio estabelecido?
- [x] A história está de acordo com o modelo do INVEST?
- [x] A história foi estimada em pontos, levando em conta os critérios de aceitação?
- [x] A história tem representação no formato de um protótipo?
- [x] A história foi validada pelo cliente?

## DoD

- [x] Os critérios de aceitação foram desenvolvidos e verificados?
- [x] O código desenvolvido está de acordo com a arquitetura do projeto?
- [ ] O código desenvolvido é responsivo com os modelos de tela estabelecidos para o projeto?
- [x] A funcionalidade desenvolvida foi revisada por um membro da equipe?
- [ ] A funcionalidade está integrada ao sistema principal da aplicação?

**Comment by weslley17w** [comment]
**INVEST**: 

| **Independente** | **Negociável** | **Valorosa** | **Estimável** | **Pequena** | **Testável** |
|------------------|----------------|--------------|---------------|-------------|--------------|
| Sim              | Sim            | Sim          | Sim           | Sim         | Sim          |

**Comment by Victor-oss** [comment]
![Screenshot from 2023-11-20 16-44-19](https://github.com/mdsreq-fga-unb/2023-2-BeachTennisCoordiMate/assets/55855365/3e5c5c6f-6e96-4736-9598-9ad10f5521ad)
![criando_conta](https://github.com/mdsreq-fga-unb/2023-2-BeachTennisCoordiMate/assets/55855365/543a9bb6-f573-448b-9904-e3e9d916e5d4)

**Comment by luciano-freitas-melo** [comment]
Valor de negócio + entendimento técnico: 7

**Comment by luciano-freitas-melo** [comment]
Pontos da história: 1
