### ISSUE TITLE
[US02] - Fazer login como administrador  

### ISSUE THREAD

**Issue by ArturRSA19** [mdsreq-fga-unb/2023-2-BeachTennisCoordiMate#46]
# US02 - Fazer login como administrador  

## Descrição

Eu, como usuário-coordenador, desejo fazer login na minha conta para acessar as funcionalidades exclusivas de coordenador

## Critérios de Aceitação

- [x] Ao acessar a página de login, o usuário-coordenador deve encontrar campos para inserir o endereço de e-mail e senha. 
- [x] Os campos e-mail e senha são obrigatórios 
- [x] O usuário deve receber uma mensagem de aviso, caso o email ou a senha estejam incorretos 

## DoR

- [x] O requisito está declarado como uma história de usuário?
- [x] A história tem critérios de aceitação definidos?
- [x] A história tem valor de negócio estabelecido?
- [x] A história está de acordo com o modelo do INVEST?
- [x] A história foi estimada em pontos, levando em conta os critérios de aceitação?
- [x] A história tem representação no formato de um protótipo?
- [x] A história foi validada pelo cliente?

## DoD

- [x] Os critérios de aceitação foram desenvolvidos e verificados?
- [x] O código desenvolvido está de acordo com a arquitetura do projeto?
- [ ] O código desenvolvido é responsivo com os modelos de tela estabelecidos para o projeto?
- [x] A funcionalidade desenvolvida foi revisada por um membro da equipe?
- [ ] A funcionalidade está integrada ao sistema principal da aplicação?

**Comment by weslley17w** [comment]
**INVEST**: 

| **Independente** | **Negociável** | **Valorosa** | **Estimável** | **Pequena** | **Testável** |
|------------------|----------------|--------------|---------------|-------------|--------------|
| Sim              | Sim            | Sim          | Sim           | Sim         | Sim          |

**Comment by Victor-oss** [comment]
![Screenshot from 2023-11-20 16-55-55](https://github.com/mdsreq-fga-unb/2023-2-BeachTennisCoordiMate/assets/55855365/6ac3c0f2-da86-4390-b9d1-0ff0401ec43f)

**Comment by luciano-freitas-melo** [comment]
Valor de negócio + entendimento técnico: 7

**Comment by luciano-freitas-melo** [comment]
Pontos por história: 1
