### ISSUE TITLE
[US049] - Criar plano de aula

### ISSUE THREAD

**Issue by ArturRSA19** [mdsreq-fga-unb/2023-2-BeachTennisCoordiMate#47]
# US49 - Criar plano de aula

## Descrição

Eu, como usuário-coordenador, desejo criar um plano de aula, para poder administrar as aulas da arena.

## Critérios de Aceitação

- [x] Ao criar um plano de aula, o usuário-coordenador deve fornecer as informações no título.
- [x] O campo título é obrigatório.
- [x] O título deverá ter no mínimo 5 caracteres
- [x] O campo objetivos deverá ter, no máximo, 600 caracteres
- [x] O campo observações deverá ter no máximo 500 caracteres
- [x] O sistema deve criar os campos "objetivos" e "observações" vazios.
## DoR

- [x] O requisito está declarado como uma história de usuário?
- [x] A história tem critérios de aceitação definidos?
- [x] A história tem valor de negócio estabelecido?
- [x] A história está de acordo com o modelo do INVEST?
- [x] A história foi estimada em pontos, levando em conta os critérios de aceitação?
- [x] A história tem representação no formato de um protótipo?
- [x] A história foi validada pelo cliente?

## DoD

- [x] Os critérios de aceitação foram desenvolvidos e verificados?
- [x] O código desenvolvido está de acordo com a arquitetura do projeto?
- [x] O código desenvolvido é responsivo com os modelos de tela estabelecidos para o projeto?
- [x] A funcionalidade desenvolvida foi revisada por um membro da equipe?
- [ ] A funcionalidade está integrada ao sistema principal da aplicação?

**Comment by weslley17w** [comment]
| **Independente** | **Negociável** | **Valorosa** | **Estimável** | **Pequena** | **Testável** |
|------------------|----------------|--------------|---------------|-------------|--------------|
| Sim              | Sim            | Sim          | Sim           | Sim         | Sim          |

**Comment by Victor-oss** [comment]
![Screenshot from 2023-11-20 17-31-11](https://github.com/mdsreq-fga-unb/2023-2-BeachTennisCoordiMate/assets/55855365/69a69983-fa41-47c2-98d6-56891ed0c7c3)
![Screenshot from 2023-11-20 17-31-22](https://github.com/mdsreq-fga-unb/2023-2-BeachTennisCoordiMate/assets/55855365/bcaadfa1-db09-4a69-9b92-510691a14654)
![plano_aula_criado](https://github.com/mdsreq-fga-unb/2023-2-BeachTennisCoordiMate/assets/55855365/2e1c2afc-99b9-4e24-b42b-41cde1c2c99c)

**Comment by luciano-freitas-melo** [comment]
Valor de negócio + entendimento técnico: 7

**Comment by luciano-freitas-melo** [comment]
pontos por história: 2
