### ISSUE TITLE
[US51] - Excluir plano de aula

### ISSUE THREAD

**Issue by JoaoBarreto03** [mdsreq-fga-unb/2023-2-BeachTennisCoordiMate#48]
# US51 - Excluir plano de aula

## Descrição

Eu, como usuário-coordenador, desejo poder excluir um plano de aula, para apagar planos de aula que estiverem obsoletos

## Critérios de Aceitação

- [x] Ao selecionar a opção de exclusão, o sistema deve solicitar uma confirmação antes de apagar o plano de aula.
- [x] O sistema deve retornar uma mensagem ao usuário confirmando a realização da ação

## DoR

- [x] O requisito está declarado como uma história de usuário?
- [x] A história tem critérios de aceitação definidos?
- [x] A história tem valor de negócio estabelecido?
- [x] A história está de acordo com o modelo do INVEST?
- [x] A história foi estimada em pontos, levando em conta os critérios de aceitação?
- [x] A história tem representação no formato de um protótipo?
- [x] A história foi validada pelo cliente?

## DoD

- [x] Os critérios de aceitação foram desenvolvidos e verificados?
- [x] O código desenvolvido está de acordo com a arquitetura do projeto?
- [x] O código desenvolvido é responsivo com os modelos de tela estabelecidos para o projeto?
- [x] A funcionalidade desenvolvida foi revisada por um membro da equipe?
- [x] A funcionalidade está integrada ao sistema principal da aplicação?

**Comment by Victor-oss** [comment]
**INVEST**: 

| **Independente** | **Negociável** | **Valorosa** | **Estimável** | **Pequena** | **Testável** |
|------------------|----------------|--------------|---------------|-------------|--------------|
| Sim              | Sim            | Sim          | Sim           | Sim         | Sim          |

**Comment by Victor-oss** [comment]
![Screenshot from 2023-11-20 18-14-00](https://github.com/mdsreq-fga-unb/2023-2-BeachTennisCoordiMate/assets/55855365/28758926-97a8-4461-8682-455daa347dcf)
![Screenshot from 2023-11-20 18-14-14](https://github.com/mdsreq-fga-unb/2023-2-BeachTennisCoordiMate/assets/55855365/0aa7ca75-d075-4496-bc60-ffae4a222a2e)
![Screenshot from 2023-11-20 18-14-47](https://github.com/mdsreq-fga-unb/2023-2-BeachTennisCoordiMate/assets/55855365/65298a83-b956-4219-9434-fbb958e74290)

**Comment by luciano-freitas-melo** [comment]
Não foi feito na sprint 12 - problema de dependência com outras histórias
Atualizado para sprint 13
