### ISSUE TITLE
[US50] - Visualizar plano de aula 

### ISSUE THREAD

**Issue by ArturRSA19** [mdsreq-fga-unb/2023-2-BeachTennisCoordiMate#49]
# US50 - Visualizar plano de aula 

## Descrição

Eu, como usuário-coordenador, desejo poder visualizar um plano de aula, para procurar por possíveis erros.

## Critérios de Aceitação

- [x] O sistema deve permitir que o usuário consiga selecionar um plano de aula para conseguir visualizar o título, a descrição, as observações e os drills.

## DoR

- [x] O requisito está declarado como uma história de usuário?
- [x] A história tem critérios de aceitação definidos?
- [x] A história tem valor de negócio estabelecido?
- [x] A história está de acordo com o modelo do INVEST?
- [x] A história foi estimada em pontos, levando em conta os critérios de aceitação?
- [x] A história tem representação no formato de um protótipo?
- [x] A história foi validada pelo cliente?

## DoD

- [x] Os critérios de aceitação foram desenvolvidos e verificados?
- [x] O código desenvolvido está de acordo com a arquitetura do projeto?
- [x] O código desenvolvido é responsivo com os modelos de tela estabelecidos para o projeto?
- [x] A funcionalidade desenvolvida foi revisada por um membro da equipe?
- [x] A funcionalidade está integrada ao sistema principal da aplicação?

**Comment by weslley17w** [comment]
**INVEST**: 

| **Independente** | **Negociável** | **Valorosa** | **Estimável** | **Pequena** | **Testável** |
|------------------|----------------|--------------|---------------|-------------|--------------|
| Sim              | Sim            | Sim          | Sim           | Sim         | Sim          |

**Comment by Victor-oss** [comment]
![Screenshot from 2023-11-20 17-44-51](https://github.com/mdsreq-fga-unb/2023-2-BeachTennisCoordiMate/assets/55855365/2e6e68af-cfc0-46e2-9e54-5184cf3609ed)
![Screenshot from 2023-11-20 17-40-37](https://github.com/mdsreq-fga-unb/2023-2-BeachTennisCoordiMate/assets/55855365/5f1a1fa4-0834-4037-a72e-4a21e3bd2b9c)

**Comment by luciano-freitas-melo** [comment]
Valor de negócio + entendimento técnico: 7

**Comment by luciano-freitas-melo** [comment]
Não finalizado na sprint 12 - 90% concluída na sprint
Atualizado para sprint 13

**Comment by luciano-freitas-melo** [comment]
História passou em todos os critérios de DoD
