### ISSUE TITLE
[US52] - Editar plano de aula

### ISSUE THREAD

**Issue by JoaoBarreto03** [mdsreq-fga-unb/2023-2-BeachTennisCoordiMate#51]
# US52 - Editar plano de aula

## Descrição

Eu, como usuário-coordenador, desejo poder editar um plano de aula, para alterar
planos de aula que estiverem com alguma informação errada:

## Critérios de Aceitação

- [x] Os campos título, objetivos e observações do plano de aula devem ser editáveis.
- [x] O sistema deve impedir o usuário de deixar o campo obrigatório "título" vazio
- [x] O título deverá ter, no mínimo, 5 caracteres
- [x] O campo objetivos deverá ter, no máximo, 600 caracteres
- [x] O campo observações deverá ter no máximo 500 caracteres

## DoR

- [x] O requisito está declarado como uma história de usuário?
- [x] A história tem critérios de aceitação definidos?
- [x] A história tem valor de negócio estabelecido?
- [x] A história está de acordo com o modelo do INVEST?
- [x] A história foi estimada em pontos, levando em conta os critérios de aceitação?
- [x] A história tem representação no formato de um protótipo?
- [x] A história foi validada pelo cliente?

## DoD

- [x] Os critérios de aceitação foram desenvolvidos e verificados?
- [x] O código desenvolvido está de acordo com a arquitetura do projeto?
- [x] O código desenvolvido é responsivo com os modelos de tela estabelecidos para o projeto?
- [x] A funcionalidade desenvolvida foi revisada por um membro da equipe?
- [x] A funcionalidade está integrada ao sistema principal da aplicação?

**Comment by Victor-oss** [comment]
**INVEST**: 

| **Independente** | **Negociável** | **Valorosa** | **Estimável** | **Pequena** | **Testável** |
|------------------|----------------|--------------|---------------|-------------|--------------|
| Sim              | Sim            | Sim          | Sim           | Sim         | Sim          |

**Comment by Victor-oss** [comment]
![Screenshot from 2023-11-20 18-36-35](https://github.com/mdsreq-fga-unb/2023-2-BeachTennisCoordiMate/assets/55855365/dab46728-2ecb-46a9-a089-0f7e9eecdd4b)
![Screenshot from 2023-11-20 18-35-20](https://github.com/mdsreq-fga-unb/2023-2-BeachTennisCoordiMate/assets/55855365/67f0162e-b682-4e3f-9365-d11a171a3ffc)

**Comment by luciano-freitas-melo** [comment]
Não finalizado na sprint 12 - não foi desenvolvida
Atualizado para sprint 13
