### ISSUE TITLE
[US53] - Baixar planos de aula

### ISSUE THREAD

**Issue by JoaoBarreto03** [mdsreq-fga-unb/2023-2-BeachTennisCoordiMate#52]
# US53 - Baixar planos de aula

## Descrição

Eu, como usuário-coordenador, desejo baixar os planos de aulas, para conseguir enviá-los aos responsáveis pela verificação dos planos, que são externos a arena:

## Critérios de Aceitação

- [x] O sistema deve gerar um arquivo de download contendo as informações completas do plano de aula com título, objetivos, observações e os drills.
- [x] Cada drill do plano de aula deve apresentar seu título, descrição, observações e a representação gráfica do treino.
- [x] O arquivo de download deve estar em um formato PDF

**Comment by Victor-oss** [comment]
**INVEST**: 

| **Independente** | **Negociável** | **Valorosa** | **Estimável** | **Pequena** | **Testável** |
|------------------|----------------|--------------|---------------|-------------|--------------|
| Sim              | Sim            | Sim          | Sim           | Sim         | Sim          |

**Comment by Victor-oss** [comment]
![Screenshot from 2023-11-20 20-02-07](https://github.com/mdsreq-fga-unb/2023-2-BeachTennisCoordiMate/assets/55855365/5d62ab37-c0c3-43f0-9370-d19f1c09bc97)
![Screenshot from 2023-11-20 20-03-29](https://github.com/mdsreq-fga-unb/2023-2-BeachTennisCoordiMate/assets/55855365/aeb9b06e-2ca2-47d1-9754-174e974abc73)
