### ISSUE TITLE
[US54] - Adicionar Drills

### ISSUE THREAD

**Issue by JoaoBarreto03** [mdsreq-fga-unb/2023-2-BeachTennisCoordiMate#53]
# US54 - Adicionar Drills

## Descrição

Eu, como usuário-coordenador, desejo adicionar um ou mais drills a um plano de
aula para declarar os diferentes drills presentes em um plano de aula

## Critérios de Aceitação

- [x] Devem ser informados os campos título, descrição e observações dos drills para adicioná-los ao plano de aula.
- [x] O campo "Título" é obrigatório
- [x] O título deverá ter, no mínimo, 5 caracteres
- [x] A descrição do drill deverá ter, no máximo, 500 caracteres
- [x] O campo observações deverá ter, no máximo, 500 caracteres

## DoR

- [x] O requisito está declarado como uma história de usuário?
- [x] A história tem critérios de aceitação definidos?
- [x] A história tem valor de negócio estabelecido?
- [x] A história está de acordo com o modelo do INVEST?
- [x] A história foi estimada em pontos, levando em conta os critérios de aceitação?
- [x] A história tem representação no formato de um protótipo?
- [x] A história foi validada pelo cliente?

## DoD

- [x] Os critérios de aceitação foram desenvolvidos e verificados?
- [x] O código desenvolvido está de acordo com a arquitetura do projeto?
- [x] O código desenvolvido é responsivo com os modelos de tela estabelecidos para o projeto?
- [x] A funcionalidade desenvolvida foi revisada por um membro da equipe?
- [x] A funcionalidade está integrada ao sistema principal da aplicação?

**Comment by Victor-oss** [comment]
**INVEST**: 

| **Independente** | **Negociável** | **Valorosa** | **Estimável** | **Pequena** | **Testável** |
|------------------|----------------|--------------|---------------|-------------|--------------|
| Sim              | Sim            | Sim          | Sim           | Sim         | Sim          |

**Comment by Victor-oss** [comment]
![Screenshot from 2023-11-20 18-54-27](https://github.com/mdsreq-fga-unb/2023-2-BeachTennisCoordiMate/assets/55855365/4cbcc01a-938b-48b0-a2ce-4218c48f13cd)
![Screenshot from 2023-11-20 18-56-17](https://github.com/mdsreq-fga-unb/2023-2-BeachTennisCoordiMate/assets/55855365/eb062916-d53f-4610-9a0d-43a37dfa5227)
![Screenshot from 2023-11-20 19-03-59](https://github.com/mdsreq-fga-unb/2023-2-BeachTennisCoordiMate/assets/55855365/5dbd743f-b1d5-4341-bf99-7705cba60a19)

**Comment by luciano-freitas-melo** [comment]
Não finalizado na sprint 12 - problemas de integração e dependência com outras histórias
Atualizado para sprint 13

- [ ] Integrar drill ao plano de aula
